### ISSUE TITLE
write_frame_snapshot restart error with name varid

### ISSUE THREAD

**Issue by kaustubanand** [MintonGroup/swiftest#48]
Collisions after restarting a swiftest simulation cause an error and crash when information is dumped (`dump_cadence`). Issue in collision_io.f90 (see below).

Error: 
NetCDF error in collision_io_netcdf_write_frame_snapshot nf90_put_var name_varid: cb (or pl)
NetCDF: Variable not found

**Comment by kaustubanand** [comment]
The above error is in RELEASE and PROFILE mode.

When using running with DEBUG or TESTING mode, a different error is found as below:

[                                               #                                ] Time =  2.19150E+03 of  3.65250E+03At line 273 of file /home/anand43/git/swiftest/src/collision/collision_util.f90
Fortran runtime error: Allocatable argument 'self' is not allocated

Error termination. Backtrace:
#0  0x155554dc172f in __collision_MOD_collision_util_index_map
        at /home/anand43/git/swiftest/src/collision/collision_util.f90:273
#1  0x155554db4bea in __collision_MOD_collision_io_netcdf_dump
        at /home/anand43/git/swiftest/src/collision/collision_io.f90:102
#2  0x155554e3fd6d in __swiftest_MOD_swiftest_io_dump_system
        at /home/anand43/git/swiftest/src/swiftest/swiftest_io.f90:392
#3  0x155554d9420c in __swiftest_MOD_swiftest_driver
        at /home/anand43/git/swiftest/src/swiftest/swiftest_driver.f90:166
#4  0x401465 in MAIN__
        at /home/anand43/git/swiftest/src/main/main.f90:23
#5  0x4014d0 in main
        at /home/anand43/git/swiftest/src/main/main.f90:15
